# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: olca.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Ref(betterproto.Message):
    """
    A Ref is a reference to a RootEntity. When serializing an entity (e.g. a
    Process) that references another standalone entity (e.g. a Flow in an
    Exchange) we do not want to write the complete referenced entity into the
    serialized object but just a reference. However, the reference contains
    some meta-data like name, category path etc. that are useful to display.
    """

    type: str = betterproto.string_field(1)
    id: str = betterproto.string_field(2)
    name: str = betterproto.string_field(3)
    description: str = betterproto.string_field(4)
    version: str = betterproto.string_field(5)
    last_change: str = betterproto.string_field(6)
    category_path: List[str] = betterproto.string_field(7)


@dataclass
class Process(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    version: str = betterproto.string_field(4)
    last_change: str = betterproto.string_field(5)
