// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.openlca.proto.services;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\021protolca.services\032\nolc" +
      "a.proto2_\n\013DataService\022%\n\004flow\022\r.protolc" +
      "a.Ref\032\016.protolca.Flow\022)\n\010put_flow\022\016.prot" +
      "olca.Flow\032\r.protolca.RefB\034\n\032org.openlca." +
      "proto.servicesP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.openlca.proto.Proto.getDescriptor(),
        });
    org.openlca.proto.Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
