// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package org.openlca.proto.services;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\021protolca.services\032\nolc" +
      "a.proto28\n\014ModelService\022(\n\007getFlow\022\r.pro" +
      "tolca.Ref\032\016.protolca.FlowB\034\n\032org.openlca" +
      ".proto.servicesP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.openlca.proto.Proto.getDescriptor(),
        });
    org.openlca.proto.Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
